version: '3'

services:
  api:
    build: ./
    depends_on:
      - db
    image: radio:latest
    container_name: radio_api
    command: gunicorn --bind 0.0.0.0:5000 run:app --workers=8 --worker-class=eventlet
    ports:
      - 5000:5000
    env_file: ./web.dev.env
  db:
    image: postgres:latest
    container_name: radio_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: ./db.dev.env

volumes:
  postgres_data: